### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by analyticalpicasso** [fnielsen/afinn#21]
Hi, 

The repo shows the LICENSE change from GPL to Apache-2.0 but not reflected in python library. Dies it still have GPL License?

**Comment by analyticalpicasso** [comment]
@fnielsen Kindly update on the License details. Thank You.

**Comment by fnielsen** [comment]
I have now made a change in `setup.py` (at first I did not notice the statement there. For the PyPI I cannot change the license (I think), but when I upload a new version I can do the change.

Let me here what precisely you issue is?

**Comment by analyticalpicasso** [comment]
Hi,

Thank You for the update. My issue is precisely on license type only. Since there was a discrepancy that whether it is GPL or Apache2 i raised the issue.

**Comment by fnielsen** [comment]
Thanks for the clarification
